[CODECEPT] github test v1.5

diff --git a/.github/workflows/codeceptjs-reporting.yml b/.github/workflows/codeceptjs-reporting.yml
--- a/.github/workflows/codeceptjs-reporting.yml
+++ b/.github/workflows/codeceptjs-reporting.yml
@@ -5,7 +5,7 @@ name: CodeceptJS example reporting results
 
 on:
   schedule:
-    - cron: "*/30 * * * *"
+    - cron: "0 8 * * *"
 
 jobs:
   reporting:
@@ -31,7 +31,7 @@ jobs:
           fail_tests=$(grep -oP '^\d+ failed' test-results.txt | grep -oP '\d+')
           echo "Number of failed tests: $fail_tests"
           if [ "$fail_tests" -gt 2 ]; then
-            echo "More than 1 failed tests. Exiting with error." exit 1;
+            echo "More than 2 failed tests. Exiting with error." exit 1;
             else exit 0;
           fi
         env:
@@ -40,5 +40,7 @@ jobs:
           CODECEPT_GROUP_TESTS: "${{ secrets.CODECEPT_GROUP_TESTS }}"
       - name: Invert success and failure
         run: echo ${{ steps.test-incorrect.outcome }}
+      - name: Number of failure
+        run: echo $fail_tests
 
 #run: if [[ ${{ steps.test-incorrect.outcome }} == "failure" ]]; then exit 0; else exit 1; fi
