[CODECEPT] github test v1.4

diff --git a/.github/workflows/codeceptjs-reporting.yml b/.github/workflows/codeceptjs-reporting.yml
--- a/.github/workflows/codeceptjs-reporting.yml
+++ b/.github/workflows/codeceptjs-reporting.yml
@@ -5,7 +5,7 @@ name: CodeceptJS example reporting results
 
 on:
   schedule:
-    - cron: "0 8 * * *"
+    - cron: "*/30 * * * *"
 
 jobs:
   reporting:
@@ -22,7 +22,7 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
       - name: Dependencies installing
-        run: npm ci
+        run: npm i
       - name: Test executing
         id: test-incorrect
         continue-on-error: true
@@ -30,9 +30,9 @@ jobs:
           npx codeceptjs run > test-results.txt
           fail_tests=$(grep -oP '^\d+ failed' test-results.txt | grep -oP '\d+')
           echo "Number of failed tests: $fail_tests"
-          if [ "$fail_tests" -gt 1 ]; then
-            echo "More than 1 failed tests. Exiting with error."
-            exit 1
+          if [ "$fail_tests" -gt 2 ]; then
+            echo "More than 1 failed tests. Exiting with error." exit 1;
+            else exit 0;
           fi
         env:
           TESTOMATIO: "${{ secrets.TESTOMATIO }}"
